const GET = "GET_COURSE_TRENDING";
const ADD = "ADD_COURSE_TRENDING";
const DETAIL = "DETAIL_COURSE_TRENDING";
const UPDATE = "UPDATE_COURSE_TRENDING";
const DELETE = "DELETE_COURSE_TRENDING";

export { GET, ADD, DETAIL, UPDATE, DELETE };
