const GET = "GET_COURSE_BUSINESS";
const ADD = "ADD_COURSE_BUSINESS";
const DETAIL = "DETAIL_COURSE_BUSINESS";
const UPDATE = "UPDATE_COURSE_BUSINESS";
const DELETE = "DELETE_COURSE_BUSINESS";

export { GET, ADD, DETAIL, UPDATE, DELETE };
