const GET = "GET_COURSE_CAREER";
const ADD = "ADD_COURSE_CAREER";
const DETAIL = "DETAIL_COURSE_CAREER";
const UPDATE = "UPDATE_COURSE_CAREER";
const DELETE = "DELETE_COURSE_CAREER";

export { GET, ADD, DETAIL, UPDATE, DELETE };
