const GET = "GET_COURSE_FLASH_SALE";
const ADD = "ADD_COURSE_FLASH_SALE";
const DETAIL = "DETAIL_COURSE_FLASH_SALE";
const UPDATE = "UPDATE_COURSE_FLASH_SALE";
const DELETE = "DELETE_COURSE_FLASH_SALE";

export { GET, ADD, DETAIL, UPDATE, DELETE };
